version: '3.7'

services:
  app:
    build: .
    container_name: app-container
    tty: true
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    networks:
      - deliveryfast-network
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=base
    volumes:
     - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - deliveryfast-network

volumes:
  postgres-volume:
    driver: local

networks:
  deliveryfast-network:
    driver: bridge